# Site settings
title: Mystery Manila
description: >
    The first live escape room game in the Philippines. One room. One mystery. One hour. One way out. Can you solve it?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mysterymanila.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

mailchimp:
    form_action: "//mysterymanila.us8.list-manage.com/subscribe/post?u=adcaf98baa115e601f7273ef6&amp;id=bd9785a80c"

sass:
  style: compressed

#Collections
collections:
    branches:
      output: true
      permalink: /branches/:name/
